---
title: "R Notebook"
name: "Hanyang Zhang"
output: html_notebook
---

## library
```{r,warning=FALSE, message=FALSE}
library(tidymodels)
library(tidyverse)
library(janitor)
library(vip)
library(skimr)
library(C50)
library(kableExtra)
library(GGally)
library(fastshap)
library(MASS)
library(rpart.plot)
library(factoextra)
library(imputeMissings)
library(ISLR)
library(tree)
library(corrplot)
```

## import data
```{r,warning=FALSE, message=FALSE}
project <- read_csv("C:\\Users\\Albert\\OneDrive - Arkansas Tech University\\Documents\\MSBA\\Fall 2022\\BAN 6025- Predicted Analysis & Data Mining\\data\\DonorMerge_Final.csv") %>% clean_names()
donor <- read_csv("C:\\Users\\Albert\\OneDrive - Arkansas Tech University\\Documents\\MSBA\\Fall 2022\\BAN 6025- Predicted Analysis & Data Mining\\data\\Donations.csv") %>% clean_names()


project %>% skim()
```

## data cleaning and manipulation
```{r}
project_prep = subset(project, select= -c(projectid, teacher_acctid, schoolid, school_ncesid, secondary_focus_subject, secondary_focus_area, school_latitude, school_longitude, school_city, school_state, school_district, school_county, school_zip, date_posted)) 


project_prep$is_exciting=as.factor(project_prep$is_exciting)
project_prep$one_non_teacher_referred_donor_g=as.factor(project_prep$one_non_teacher_referred_donor_g)
project_prep$school_charter=as.factor(project_prep$school_charter)
project_prep$school_magnet=as.factor(project_prep$school_magnet)
project_prep$school_year_round=as.factor(project_prep$school_year_round)
project_prep$school_nlns=as.factor(project_prep$school_nlns)
project_prep$school_kipp=as.factor(project_prep$school_kipp)
project_prep$school_charter_ready_promise=as.factor(project_prep$school_charter_ready_promise)
project_prep$teacher_teach_for_america=as.factor(project_prep$teacher_teach_for_america)
project_prep$teacher_ny_teaching_fellow=as.factor(project_prep$teacher_ny_teaching_fellow)
project_prep$eligible_double_your_impact_matc=as.factor(project_prep$eligible_double_your_impact_matc)
project_prep$eligible_almost_home_match=as.factor(project_prep$eligible_almost_home_match)
newproject <- project_prep
```

## exploratory analysis
```{r}
# distribution of exciting project (y)
project_summary <- newproject %>%
  count(is_exciting) %>%
  mutate(pct = n/sum(n))


project_summary %>%
  ggplot(aes(x=factor(is_exciting),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="Distribution of exiciting project", x="Exciting Projects", y="PCT")
# Distribution of teacher prefix
prefix <- project_prep %>%
  count(teacher_prefix) %>%
  mutate(pct = n/sum(n))

prefix %>% ggplot(aes(x=factor(teacher_prefix),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="Distribution in each teacher prefix", x="Teacher Prefix", y="PCT")
# Distribution of metro area
metro <- project_prep %>%
  count(school_metro) %>%
  mutate(pct = n/sum(n))

metro %>%
  ggplot(aes(x=factor(school_metro),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="distribution in each school metro", x="metro", y="PCT")
# Distribution of primary focus subject
primary_subject <- project_prep %>%
  count(primary_focus_subject) %>%
  mutate(pct = n/sum(n))

primary_subject %>%
  ggplot(aes(x=factor(primary_focus_subject),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2, colour = "white") + 
  labs(title="distribution in primary focus subject", x="primary focus subject", y="PCT")+theme(axis.text.x = element_text(angle = 90))
# Distribution of primary focus area
primary_area <- project_prep %>%
  count(primary_focus_area) %>%
  mutate(pct = n/sum(n))

primary_area %>%
  ggplot(aes(x=factor(primary_focus_area),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 1, colour = "white") + 
  labs(title="distribution in primary focus area", x="primary focus area", y="PCT")+theme(axis.text.x = element_text(angle = 90))
# Distribution of poverty level
poverty <- project_prep %>%
  count(poverty_level) %>%
  mutate(pct = n/sum(n))

poverty %>%
  ggplot(aes(x=factor(poverty_level),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="distribution in poverty level", x="poverty level", y="PCT")
# Distribution of grade level
grade <- project_prep %>%
  count(grade_level) %>%
  mutate(pct = n/sum(n))

grade %>%
  ggplot(aes(x=factor(grade_level),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="distribution in grade level", x="grade level", y="PCT")

# Distribution of great message proportion
great_message<-project_prep %>% 
              filter(total_price_excluding_optional_s<20000, total_price_including_optional_s<20000,students_reached<20000)
#great_messages_proportion
great_message %>%
  ggplot(aes(x=great_messages_proportion, fill=factor(is_exciting))) +
  geom_histogram(bins=25) +
  labs(title="relationship of exciting projects by great messages proportion", x="great messages proportion", y="Count")


```

## data partitioning (train/test)
```{r}
project_prep<- newproject %>% 
  filter(total_price_excluding_optional_s<10000, total_price_including_optional_s<10000,students_reached<10000)
  
set.seed(1208)
x <- initial_split(newproject, prop = 0.75)
train <- training(x)
test  <- testing(x)
```

## build and bake recipe
```{r}
project_recipe <-
  recipe(is_exciting ~ .,data = train)%>%
  step_impute_median(all_numeric_predictors()) %>% # missing values numeric 
  step_novel(all_nominal_predictors()) %>% # new factor levels 
  step_unknown(all_nominal_predictors()) %>% # missing values 
  step_other(all_nominal_predictors(),threshold = 0.01) %>%  # pool rarely occuring levels 
  step_dummy(all_nominal_predictors(), one_hot = TRUE) %>%
  step_nzv(all_predictors())

bake_train <- bake(project_recipe %>% prep(), train)
bake_test <- bake(project_recipe %>% prep(),test)

```

## logistic regression method
```{r}
## full model
log_model <-logistic_reg(mode = "classification") %>%
                  set_engine("glm") %>%
                  fit(is_exciting ~ ., data = bake_train)

tidy(log_model) %>%
  mutate_at(c("estimate", "std.error", "statistic", "p.value"),round, 4)


## new model with significant vars
log_model2 <-logistic_reg(mode = "classification") %>%
                  set_engine("glm") %>%
                  fit(is_exciting ~ great_messages_proportion + teacher_referred_count + non_teacher_referred_count + fulfillment_labor_materials + total_price_excluding_optional_s + total_price_including_optional_s + school_metro_rural + school_charter_FALSE. + teacher_teach_for_america_FALSE. + primary_focus_subject_Special.Needs	+ eligible_double_your_impact_matc_FALSE. + eligible_almost_home_match_FALSE., data = bake_train)

tidy(log_model2) %>%
  mutate_at(c("estimate", "std.error", "statistic", "p.value"),round, 4)

# -- training predictions from new logistic model
predict(log_model2, bake_train, type = "prob") %>%
  bind_cols(.,predict(log_model2, bake_train)) %>%
  bind_cols(.,bake_train) -> scored_train_log_model2

head( scored_train_log_model2)

# -- testing predictions from new logistic model
predict(log_model2, bake_test, type = "prob") %>%
  bind_cols(.,predict(log_model2, bake_test)) %>%
  bind_cols(.,bake_test) -> scored_test_log_model2

head(scored_test_log_model2)

# -- AUC: Train and Test 
scored_train_log_model2 %>% 
  metrics(is_exciting, .pred_FALSE, estimate = .pred_class) %>%
  mutate(part="training") %>%
  bind_rows( scored_test_log_model2 %>% 
               metrics(is_exciting, .pred_FALSE, estimate = .pred_class) %>%
               mutate(part="testing") 
  )

# precision and recall
  scored_train_log_model2 %>% 
    precision(is_exciting, .pred_class, event_level = 'second') %>%
    mutate(part="training") %>%
    bind_rows( scored_test_log_model2 %>% 
                 precision(is_exciting,  .pred_class, event_level = 'second') %>%
                 mutate(part="testing") )  %>% print()
    
   scored_train_log_model2 %>% 
    recall(is_exciting, .pred_class) %>%
    mutate(part="training") %>%
    bind_rows( scored_test_log_model2 %>% 
                 recall(is_exciting,  .pred_class) %>%
                 mutate(part="testing") )  %>% print()
# -- ROC Charts 
scored_train_log_model2 %>%
  mutate(model = "train") %>%
  bind_rows(scored_test_log_model2 %>%
              mutate(model="test")) %>%
  group_by(model) %>%
  roc_curve(is_exciting, .pred_FALSE) %>%
  autoplot()

## confusion matrix
scored_train_log_model2 %>%
  conf_mat(is_exciting, .pred_class) %>%
  autoplot( type = "heatmap") +
  labs(title="Train Confusion Matrix")

scored_test_log_model2 %>%
  conf_mat(is_exciting, .pred_class) %>%
  autoplot( type = "heatmap") +
  labs(title="Test Confusion Matrix")

  
```

## random forest tunning
```{r}
rf_model_1 <- rand_forest(trees=100, min_n = 10) %>%
  set_mode("classification") %>%
  set_engine("ranger", importance="impurity", num.threads = 8, max.depth = 10)


rf_workflow_1 <- workflow() %>%
  add_recipe(project_recipe) %>%
  add_model(rf_model_1) %>% 
  fit(train)

```

## random forest evaluation
```{r}
model_eval <- function(model_fit, model_name){
  # -- score training  
  options(yardstick.event_first = TRUE)
  predict(model_fit, train, type="prob") %>%
    bind_cols(predict(model_fit, train, type="class")) %>%
    bind_cols(.,train)-> scored_train 

  # -- score testing 
  predict(model_fit, test, type="prob") %>%
      bind_cols(predict(model_fit,  test, type="class")) %>%
       bind_cols(., test) -> scored_test  
  
  scored_train %>% 
    metrics(is_exciting, .pred_FALSE, estimate = .pred_class) %>%
    mutate(part="training") %>%
    bind_rows( scored_test %>% 
                 metrics(is_exciting, .pred_FALSE, estimate = .pred_class) %>%
                 mutate(part="testing") ) %>%
    filter(.metric %in% c('accuracy','roc_auc')) %>%
    pivot_wider(names_from = .metric, values_from=.estimate)  %>% print()
  
  scored_train %>% 
    precision(is_exciting, .pred_class, event_level = 'second') %>%
    mutate(part="training") %>%
    bind_rows( scored_test %>% 
                 precision(is_exciting,  .pred_class, event_level = 'second') %>%
                 mutate(part="testing") )  %>% print()
    
   scored_train %>% 
    recall(is_exciting, .pred_class) %>%
    mutate(part="training") %>%
    bind_rows( scored_test %>% 
                 recall(is_exciting,  .pred_class) %>%
                 mutate(part="testing") )  %>% print()
   
  scored_test %>% 
  conf_mat(is_exciting,.pred_class) %>% 
    autoplot(type = "heatmap") %>% 
    labs(title="confusion matrix") %>%
    print() 
  
  roc <- scored_train %>% 
    mutate(part="training") %>%
     bind_rows(scored_test%>% mutate(part="test")) %>%
     group_by(part) %>%
     roc_curve(is_exciting,.pred_FALSE) %>%
     autoplot() + 
     geom_vline(xintercept=0.05,color="red",linetype = "longdash") +
     geom_vline(xintercept=0.25,color="blue",linetype = "longdash") +
    geom_vline(xintercept=0.75,color="green",linetype = "longdash") +
    labs(title=paste("ROC Curve:",model_name) , x="FPR(1 - specificity)",y="TPR(recall or sensitivity)") 
   
  hist <- scored_test %>% 
    ggplot(aes(.pred_FALSE, fill=is_exciting))+
    geom_histogram(bins=50) +
    geom_vline(xintercept=0.5,color="red") +
    labs(title=paste("Distribution of the Probabilty of Fraud:",model_name) , x=".pred_FALSE",y="count") 
  
  print(hist)
  
  print(roc)
   
   scored_test %>%
     roc_curve(is_exciting, .pred_FALSE)  %>%
     mutate(
       fpr = round((1 - specificity), 2),
       tpr = round(sensitivity, 3),
       score_threshold =  round(.threshold, 3)
     ) %>%
     group_by(fpr) %>%
     summarise(threshold = min(score_threshold),
               tpr = min(tpr)) %>%
     filter(fpr <= 0.1) %>% print()
   
    scored_test %>%
     roc_curve(is_exciting, .pred_FALSE)  %>%
     mutate(
       fpr = round((1 - specificity), 3),
       tpr = round(sensitivity, 3),
       threshold =  round(.threshold, 1)
     ) %>%
     group_by(threshold) %>%
     summarise(fpr = min(fpr),
               tpr = max(tpr)) %>%
     filter(threshold > 0  ) %>% print()
    
    scored_test %>%
     roc_curve(is_exciting, .pred_FALSE)  %>%
     mutate(
       fpr = round((1 - specificity), 3),
       tpr = round(sensitivity, 1),
       threshold =  round(.threshold, 3)
     ) %>%
     group_by(tpr) %>%
     summarise(fpr = min(fpr),
               threshold = max(threshold)) %>%
     filter(tpr >= 0  ) %>% print()
     
}
model_eval(rf_workflow_1, "random forest trees=100,min_n = 10")

# vip chart
rf_workflow_1 %>%
  extract_fit_parsnip() %>%
  vip(10)
```


# donor charactertics Clusting Analysis
```{r}
cluster <- donor %>% 
  filter(donation_total>=0 & donation_total<=500000) %>% 
  filter(donation_optional_support>=0& donation_optional_support<=500000)

cluster = subset(cluster, select= -c(donationid, projectid, donor_acctid, donor_city, donor_state, donor_zip, donation_timestamp, donation_message))

cluster$amt_under_10<-if_else(cluster$dollar_amount=='under_10',1,0)
cluster$amt_10_to_100<-if_else(cluster$dollar_amount=='10_to_100',1,0)
cluster$amt_100_and_up<-if_else(cluster$dollar_amount=='100_and_up',1,0)

cluster$pmt_creditcard<-if_else(cluster$payment_method=='creditcard',1,0)
cluster$pmt_nocash<-if_else(cluster$payment_method=='no_cash_received',1,0)
cluster$pmt_paypal<-if_else(cluster$payment_method=='paypal',1,0)
cluster$pmt_promocode<-if_else(cluster$payment_method=='promo_code_match',1,0)
cluster$pmt_doubleimpact<-if_else(cluster$payment_method=='double_your_impact_match',1,0)
cluster$pmt_amazon<-if_else(cluster$payment_method=='amazon',1,0)
cluster$pmt_check<-if_else(cluster$payment_method=='check',1,0)
cluster$pmt_almosthome<-if_else(cluster$payment_method=='almost_home_match',1,0)

cluster$is_teacher_acct <- if_else(cluster$is_teacher_acct == 'TRUE',1,0)
cluster$payment_included_acct_credit <- if_else(cluster$payment_included_acct_credit == 'TRUE',1,0)
cluster$payment_included_campaign_gift_card <- if_else(cluster$payment_included_campaign_gift_card == 'TRUE',1,0)
cluster$payment_included_web_purchased_gift_card <- if_else(cluster$payment_included_web_purchased_gift_card == 'TRUE',1,0)
cluster$payment_was_promo_matched <- if_else(cluster$payment_was_promo_matched == 'TRUE',1,0)
cluster$via_giving_page <- if_else(cluster$via_giving_page == 'TRUE',1,0)
cluster$for_honoree <- if_else(cluster$for_honoree == 'TRUE',1,0)
cluster$donation_included_optional_support <- if_else(cluster$donation_included_optional_support == 'TRUE',1,0)


newcluster = subset(cluster, select= -c(dollar_amount, payment_method, donation_to_project,donation_optional_support, donation_total))


fviz_nbclust(sample_n(newcluster,1000), kmeans, method="wss")

set.seed(1208)

donor_cluster <- kmeans(newcluster, 5, iter.max = 200, nstart = 10)
print(donor_cluster)

fviz_cluster(donor_cluster,newcluster,ellipse.type="norm",geom="point")

cluster <- as.factor(donor_cluster$cluster)
#determine which variables are driving the cluster creation

tree.clusters=tree(cluster~.,newcluster) # Where using all the variables 


summary(tree.clusters)
plot(tree.clusters)
text(tree.clusters,pretty=0)

newcluster %>% skim()
```
# Analyze the cluster
```{r}
ggplot(newcluster,aes(cluster))+geom_bar()

ggplot(newcluster,aes(x=amt_under_10))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=amt_10_to_100))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=amt_100_and_up))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=is_teacher_acct))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=donation_included_optional_support))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=payment_included_acct_credit))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=payment_included_campaign_gift_card))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=payment_included_web_purchased_gift_card))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=payment_was_promo_matched))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=via_giving_page))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=for_honoree))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_creditcard))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_nocash))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_paypal))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_promocode))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_doubleimpact))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_amazon))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_check))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)

ggplot(newcluster,aes(x=pmt_almosthome))+geom_histogram(binwidth=1) + facet_wrap(~donor_cluster$cluster)
```








